# ---
# - name: Install NVM
#   ansible.builtin.git:
#     repo: 'https://github.com/nvm-sh/nvm.git'
#     dest: "{{ ansible_env.HOME}}/.nvm/nvm.sh"

---
- name: Fetch the latest Zellij release
  shell: >
    curl -s https://api.github.com/repos/zellij-org/zellij/releases/latest |
    grep "browser_download_url.*x86_64-unknown-linux-musl.tar.gz" |
    cut -d '"' -f 4 |
    wget -i -

- name: Extract the archive 
  shell: |
    tar -xzf zellij-x86_64-unknown-linux-musl.tar.gz
  args:
    executable: /bin/bash
    
- name: Move the binary to /usr/local/bin
  shell: |
    sudo mv zellij /usr/local/bin/
  args:
    executable: /bin/bash
  become: yes

- name: Clean up
  shell: |
    rm zellij-x86_64-unknown-linux-musl.tar.gz

- name: Verify installation
  shell: |
    zellij --version

