---
- name: Update packages and reboot if required
  # https://stackoverflow.com/a/36361222/13172236
  hosts: "{{ setupHosts }}"
  vars_prompt:
    - name: setupHosts
      prompt: Which hosts would you like to use?
      private: false
  roles:
    - common
