---
- name: Install user softwares
  # https://stackoverflow.com/a/36361222/13172236
  hosts: "{{ setupHosts }}"
  vars:
    run_install: true
    run_upgrade: false
  vars_prompt:
    - name: setupHosts
      prompt: Which hosts would you like to use?
      private: false
  tasks:
    - ansible.builtin.command: echo
  roles:
    - zsh
    - nvm_node_pm2
    - zellij
    - neovim
