# ---
# - name: Install NVM
#   ansible.builtin.git:
#     repo: 'https://github.com/nvm-sh/nvm.git'
#     dest: "{{ ansible_env.HOME}}/.nvm/nvm.sh"

---
- name: Install nvm
  ansible.builtin.shell:
    creates: /home/{{
    cmd: curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh ansible_user_id }}/.nvm/nvm.sh
- name: Source NVM script and install Node.js
  ansible.builtin.shell: |
    source ~/.nvm/nvm.sh &&
    nvm install --lts
  args:
    executable: /bin/bash

- name: Include task to find node path (before first npm task)
  ansible.builtin.include_tasks: find_current_npm_executable.yml
- name: Install PM2
  community.general.npm:
    name: pm2
    global: true
    executable: "{{ npm_path }}"
  environment:
    PATH: "{{ node_dir }}:{{ ansible_env.PATH }}"
