---
- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true
    cache_valid_time: 300
  become: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
  become: true

- name: Resurrect pm2 after reboot if pm2 is installed
  ansible.builtin.shell: pm2 resurrect
  args:
    executable: /bin/zsh
  when: reboot_required_file.stat.exists and ansible_local.pm2 is defined
