---
- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true
    cache_valid_time: 300
  become: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes
    autoclean: yes
  become: true
